/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @brief STM32U073RCTX bare-metal Wi-Fi scan sample using nRF70 BM library.
 *
 * This file is structured in STM32CubeIDE style: CubeMX generates peripheral
 * init code (MX_*_Init functions), and user code is placed in the designated
 * "USER CODE" regions.
 *
 * HOW IT WORKS
 * ------------
 * 1. CubeMX initialises clocks, SPI1, GPIO, UART, and the EXTI for HOST_IRQ.
 * 2. DWT cycle counter is enabled for microsecond-resolution busy-wait.
 * 3. nrf70_bm_sys_init() loads firmware, brings up the nRF70 RPU, and
 *    configures the scan-only mode.
 * 4. nrf70_bm_sys_scan_start() triggers a Wi-Fi scan.
 * 5. The superloop calls nrf70_process_timers() and nrf70_process_work() to
 *    service the driver cooperatively (no RTOS needed).
 * 6. Scan results arrive in scan_result_cb() and are printed via UART.
 *
 * IMPORTANT: In HAL_GPIO_EXTI_Callback(), call nrf70_host_irq_handler() to
 *            dispatch the HOST_IRQ to the driver.
 */

/* USER CODE BEGIN Includes */
#include "autoconf.h"              /* CONFIG_* defines — include first */
#include "nrf70_bm_board_config.h" /* Pin assignments */
#include "system/nrf70_bm_lib.h"   /* nrf70_bm_sys_init / scan API */
#include "shim.h"                  /* nrf_wifi_os_bm_ops */
#include "work.h"                  /* nrf70_process_work() */
#include "timer.h"                 /* nrf70_process_timers() */
#include "rpu_hw_if.h"             /* nrf70_host_irq_handler() */
#include <stdio.h>
#include <string.h>
/* USER CODE END Includes */

/* --------------------------------------------------------------------------
 * CubeMX-generated peripheral handles.
 * CubeMX will also declare them in main.h; keep in sync.
 * --------------------------------------------------------------------------*/
SPI_HandleTypeDef  hspi1;
UART_HandleTypeDef huart2;

/* USER CODE BEGIN PV */
static volatile bool g_scan_done = false;
/* USER CODE END PV */

/* --------------------------------------------------------------------------
 * Forward declarations of CubeMX-generated init functions
 * --------------------------------------------------------------------------*/
static void SystemClock_Config(void);
static void MX_GPIO_Init(void);
static void MX_SPI1_Init(void);
static void MX_USART2_UART_Init(void);

/* --------------------------------------------------------------------------
 * Retarget printf to UART2 (newlib _write syscall)
 * --------------------------------------------------------------------------*/
/* USER CODE BEGIN 0 */
int _write(int file, char *ptr, int len)
{
    (void)file;
    HAL_UART_Transmit(&huart2, (uint8_t *)ptr, (uint16_t)len, HAL_MAX_DELAY);
    return len;
}
/* USER CODE END 0 */

/* --------------------------------------------------------------------------
 * Scan result callback — signature matches nrf70_bm_sys_scan_result_cb_t
 * --------------------------------------------------------------------------*/
/* USER CODE BEGIN 1 */
static void scan_result_cb(struct nrf70_bm_sys_scan_result *entry)
{
    if (entry == NULL) {
        /* NULL signals end-of-scan */
        printf("\r\n[scan] Scan complete.\r\n");
        g_scan_done = true;
        return;
    }

    /* entry->ssid is a uint8_t[NR70_SCAN_SSID_MAX_LEN], entry->ssid_len gives length */
    printf("[scan] SSID: %-32.*s  BSSID: %02X:%02X:%02X:%02X:%02X:%02X"
           "  RSSI: %d dBm  Ch: %u\r\n",
           entry->ssid_len, (const char *)entry->ssid,
           entry->bssid[0], entry->bssid[1], entry->bssid[2],
           entry->bssid[3], entry->bssid[4], entry->bssid[5],
           (int)entry->rssi,
           (unsigned)entry->channel);
}
/* USER CODE END 1 */

/* ==========================================================================
 * main()
 * ========================================================================== */
int main(void)
{
    /* USER CODE BEGIN Init */
    /* USER CODE END Init */

    /* MCU configuration — generated by CubeMX */
    HAL_Init();
    SystemClock_Config();

    /* USER CODE BEGIN SysInit */
    /* Enable DWT cycle counter for microsecond busy-wait in shim.c */
#if defined(DWT) && defined(CoreDebug)
    CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
    DWT->CYCCNT = 0;
    DWT->CTRL  |= DWT_CTRL_CYCCNTENA_Msk;
#endif
    /* USER CODE END SysInit */

    /* Peripheral init — generated by CubeMX */
    MX_GPIO_Init();
    MX_SPI1_Init();
    MX_USART2_UART_Init();

    /* USER CODE BEGIN 2 */
    printf("\r\n========================================\r\n");
    printf("  nRF70 BM Wi-Fi Scan - STM32U073RCTX\r\n");
    printf("========================================\r\n\r\n");

    /* MAC address: all-zeros → library reads from OTP */
    uint8_t mac_addr[6] = {0};

    /* Regulatory info: country code (char[2], NOT NUL-terminated) */
    struct nrf70_bm_regulatory_info reg_info = {
        .country_code = {'U', 'S'},
        .force        = false,
    };

    /* Initialise the nRF70 BM library */
    int ret = nrf70_bm_sys_init(mac_addr, &reg_info);
    if (ret != 0) {
        printf("[main] nrf70_bm_sys_init failed: %d\r\n", ret);
        while (1) { }
    }

    printf("[main] nRF70 initialised. Starting Wi-Fi scan...\r\n\r\n");

    /* Configure scan parameters */
    struct nrf70_bm_sys_scan_params scan_params = {
        .scan_type         = NRF70_SCAN_TYPE_ACTIVE,
        .dwell_time_active  = 50,   /* ms per channel */
        .dwell_time_passive = 130,  /* ms for passive channels */
        .max_bss_cnt        = 0,    /* 0 = no limit */
    };

    ret = nrf70_bm_sys_scan_start(&scan_params, scan_result_cb);
    if (ret != 0) {
        printf("[main] nrf70_bm_sys_scan_start failed: %d\r\n", ret);
    }
    /* USER CODE END 2 */

    /* =======================================================================
     * Superloop
     * ======================================================================= */
    while (1) {
        /* USER CODE BEGIN WHILE */

        /* Service expired software timers */
        nrf70_process_timers();

        /* Execute deferred work items (bottom-half processing) */
        nrf70_process_work();

        /* Restart scan every 10 seconds after scan completes */
        if (g_scan_done) {
            g_scan_done = false;
            HAL_Delay(10000);
            printf("\r\n[main] Starting next scan...\r\n\r\n");
            nrf70_bm_sys_scan_start(&scan_params, scan_result_cb);
        }

        /* USER CODE END WHILE */
    }
}

/* ==========================================================================
 * EXTI callback — called from HAL_GPIO_EXTI_IRQHandler()
 * MUST dispatch to nrf70_host_irq_handler() for HOST_IRQ pin.
 * ========================================================================== */
/* USER CODE BEGIN 4 */
void HAL_GPIO_EXTI_Callback(uint16_t GPIO_Pin)
{
    if (GPIO_Pin == NRF70_IRQ_PIN) {
        /* Dispatch HOST_IRQ to the nRF70 driver */
        nrf70_host_irq_handler();

        /* Run any work items queued by the IRQ handler immediately */
        nrf70_process_work();
    }
}
/* USER CODE END 4 */

/* ==========================================================================
 * CubeMX-generated peripheral initialisation stubs.
 * Replace these bodies with the code generated by CubeMX for your board.
 * ========================================================================== */

/**
 * @brief System Clock Configuration (HSI → PLL → 48 MHz SYSCLK).
 *        Replace with CubeMX-generated SystemClock_Config() for STM32U073.
 */
static void SystemClock_Config(void)
{
    RCC_OscInitTypeDef RCC_OscInitStruct = {0};
    RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

    RCC_OscInitStruct.OscillatorType      = RCC_OSCILLATORTYPE_HSI;
    RCC_OscInitStruct.HSIState            = RCC_HSI_ON;
    RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
    RCC_OscInitStruct.PLL.PLLState        = RCC_PLL_ON;
    RCC_OscInitStruct.PLL.PLLSource       = RCC_PLLSOURCE_HSI;
    RCC_OscInitStruct.PLL.PLLM            = RCC_PLLM_DIV1;
    RCC_OscInitStruct.PLL.PLLN            = 6;   /* VCO = 16*6 = 96 MHz */
    RCC_OscInitStruct.PLL.PLLP            = RCC_PLLP_DIV2;
    RCC_OscInitStruct.PLL.PLLQ            = RCC_PLLQ_DIV2;
    RCC_OscInitStruct.PLL.PLLR            = RCC_PLLR_DIV2; /* SYSCLK = 48 MHz */
    HAL_RCC_OscConfig(&RCC_OscInitStruct);

    RCC_ClkInitStruct.ClockType      = RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_SYSCLK |
                                       RCC_CLOCKTYPE_PCLK1;
    RCC_ClkInitStruct.SYSCLKSource   = RCC_SYSCLKSOURCE_PLLCLK;
    RCC_ClkInitStruct.AHBCLKDivider  = RCC_SYSCLK_DIV1;
    RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
    HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_1);
}

/**
 * @brief SPI1 Initialisation — CPOL=0, CPHA=0, 8-bit MSB, ~6 MHz.
 *        Replace with CubeMX-generated MX_SPI1_Init().
 */
static void MX_SPI1_Init(void)
{
    __HAL_RCC_SPI1_CLK_ENABLE();

    hspi1.Instance               = SPI1;
    hspi1.Init.Mode              = SPI_MODE_MASTER;
    hspi1.Init.Direction         = SPI_DIRECTION_2LINES;
    hspi1.Init.DataSize          = SPI_DATASIZE_8BIT;
    hspi1.Init.CLKPolarity       = SPI_POLARITY_LOW;    /* CPOL=0 */
    hspi1.Init.CLKPhase          = SPI_PHASE_1EDGE;     /* CPHA=0 */
    hspi1.Init.NSS               = SPI_NSS_SOFT;        /* CS bit-banged */
    hspi1.Init.BaudRatePrescaler = SPI_BAUDRATEPRESCALER_8; /* 48/8 = 6 MHz */
    hspi1.Init.FirstBit          = SPI_FIRSTBIT_MSB;
    hspi1.Init.TIMode            = SPI_TIMODE_DISABLE;
    hspi1.Init.CRCCalculation    = SPI_CRCCALCULATION_DISABLE;
    HAL_SPI_Init(&hspi1);
}

/**
 * @brief USART2 Initialisation — 115200 baud, 8N1 for printf redirect.
 *        Replace with CubeMX-generated MX_USART2_UART_Init().
 */
static void MX_USART2_UART_Init(void)
{
    __HAL_RCC_USART2_CLK_ENABLE();

    huart2.Instance          = USART2;
    huart2.Init.BaudRate     = 115200;
    huart2.Init.WordLength   = UART_WORDLENGTH_8B;
    huart2.Init.StopBits     = UART_STOPBITS_1;
    huart2.Init.Parity       = UART_PARITY_NONE;
    huart2.Init.Mode         = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl    = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;
    HAL_UART_Init(&huart2);
}

/**
 * @brief GPIO Initialisation — SPI1 AF pins, CS/BUCKEN/IOVDD outputs, HOST_IRQ EXTI.
 *        Replace with CubeMX-generated MX_GPIO_Init().
 */
static void MX_GPIO_Init(void)
{
    GPIO_InitTypeDef gpio = {0};

    /* Enable clocks */
    __HAL_RCC_GPIOA_CLK_ENABLE();
    __HAL_RCC_GPIOB_CLK_ENABLE();
    __HAL_RCC_GPIOC_CLK_ENABLE();

    /* SPI1 AF pins: PA5=SCK, PA6=MISO, PA7=MOSI */
    gpio.Pin       = GPIO_PIN_5 | GPIO_PIN_6 | GPIO_PIN_7;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_NOPULL;
    gpio.Speed     = GPIO_SPEED_FREQ_HIGH;
    gpio.Alternate = GPIO_AF0_SPI1;  /* Verify in STM32U073 AF table */
    HAL_GPIO_Init(GPIOA, &gpio);

    /* UART2: PA2=TX, PA3=RX */
    gpio.Pin       = GPIO_PIN_2 | GPIO_PIN_3;
    gpio.Mode      = GPIO_MODE_AF_PP;
    gpio.Pull      = GPIO_NOPULL;
    gpio.Speed     = GPIO_SPEED_FREQ_LOW;
    gpio.Alternate = GPIO_AF1_USART2;
    HAL_GPIO_Init(GPIOA, &gpio);

    /* CS (PA4) — output, HIGH = deasserted */
    gpio.Pin       = NRF70_CS_PIN;
    gpio.Mode      = GPIO_MODE_OUTPUT_PP;
    gpio.Pull      = GPIO_NOPULL;
    gpio.Speed     = GPIO_SPEED_FREQ_LOW;
    gpio.Alternate = 0;
    HAL_GPIO_Init(NRF70_CS_PORT, &gpio);
    HAL_GPIO_WritePin(NRF70_CS_PORT, NRF70_CS_PIN, GPIO_PIN_SET);

    /* BUCKEN (PC0) — output, LOW initially */
    gpio.Pin = NRF70_BUCKEN_PIN;
    HAL_GPIO_Init(NRF70_BUCKEN_PORT, &gpio);
    HAL_GPIO_WritePin(NRF70_BUCKEN_PORT, NRF70_BUCKEN_PIN, GPIO_PIN_RESET);

    /* IOVDD_CTRL (PC1) — output, LOW initially */
    gpio.Pin = NRF70_IOVDD_CTRL_PIN;
    HAL_GPIO_Init(NRF70_IOVDD_CTRL_PORT, &gpio);
    HAL_GPIO_WritePin(NRF70_IOVDD_CTRL_PORT, NRF70_IOVDD_CTRL_PIN, GPIO_PIN_RESET);

    /* HOST_IRQ (PB0) — rising-edge EXTI input */
    gpio.Pin  = NRF70_IRQ_PIN;
    gpio.Mode = GPIO_MODE_IT_RISING;
    gpio.Pull = GPIO_NOPULL;
    HAL_GPIO_Init(NRF70_IRQ_PORT, &gpio);

    /* Enable EXTI0 in NVIC (PB0 → EXTI line 0) */
    HAL_NVIC_SetPriority(EXTI0_IRQn, 5, 0);
    HAL_NVIC_EnableIRQ(EXTI0_IRQn);
}
