/*
 * Copyright (c) 2024 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @brief Manual CONFIG_* definitions for STM32 bare-metal build.
 *        Replaces Kconfig/autoconf.h generated by Zephyr build system.
 *        Include this file first via forced include or explicit #include.
 */

#ifndef __NRF70_AUTOCONF_H__
#define __NRF70_AUTOCONF_H__

/* Operation mode: scan only */
#define CONFIG_NRF70_BM_SCAN_ONLY         1

/* Board type: custom (user must supply TX power ceiling header) */
#define CONFIG_NRF70_BOARD_TYPE_CUSTOM    1

/* Bus: SPI (STM32U073 has no QSPI/OCTOSPI) */
#define CONFIG_NRF70_ON_SPI               1

/* MAC address source: use OTP-programmed MAC */
#define CONFIG_NRF70_OTP_MAC_ADDRESS      1

/* Low-power mode: disabled initially for simplicity */
/* #define CONFIG_NRF_WIFI_LOW_POWER      1 */

/* Work queue pool size */
#define CONFIG_NRF70_WORKQ_MAX_ITEMS      10

/* Maximum number of software timers */
#define CONFIG_NRF70_MAX_TIMERS           8

/* PCB loss and antenna gain (2.4 GHz) — update with measured values */
#define CONFIG_NRF70_PCB_LOSS_2G          0
#define CONFIG_NRF70_ANT_GAIN_2G          0

/* PCB loss and antenna gain (5 GHz bands) */
#define CONFIG_NRF70_PCB_LOSS_5G_BAND1    0
#define CONFIG_NRF70_PCB_LOSS_5G_BAND2    0
#define CONFIG_NRF70_PCB_LOSS_5G_BAND3    0
#define CONFIG_NRF70_ANT_GAIN_5G_BAND1   0
#define CONFIG_NRF70_ANT_GAIN_5G_BAND2   0
#define CONFIG_NRF70_ANT_GAIN_5G_BAND3   0

/* Regulatory domain */
#define CONFIG_NRF_WIFI_2G_BAND           1

/* Log level: 0=off 1=err 2=wrn 3=inf 4=dbg */
#define CONFIG_NRF70_BM_LOG_LEVEL         3

/* Heap: STM32 newlib heap is used (malloc/free) */

#endif /* __NRF70_AUTOCONF_H__ */
